"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb
*/

import { useEffect, useMemo, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";
import type { GLTF } from "three-stdlib";

const MODEL_PATH = "/models/optimized-room.glb";

type RoomNodeName =
  | "_________6_blinn1_0"
  | "body1_blinn1_0"
  | "cabin_blinn1_0"
  | "chair_body_blinn1_0"
  | "comp_blinn1_0"
  | "emis_lambert1_0"
  | "handls_blinn1_0"
  | "keyboard_blinn1_0"
  | "kovrik_blinn1_0"
  | "lamp_bl_blinn1_0"
  | "lamp_white_blinn1_0"
  | "miuse_blinn1_0"
  | "monitor2_blinn1_0"
  | "monitor3_blinn1_0"
  | "pCylinder5_blinn1_0"
  | "pillows_blinn1_0"
  | "polySurface53_blinn1_0"
  | "radiator_blinn1_0"
  | "radiator_blinn1_0001"
  | "railing_blinn1_0"
  | "red_bttns_blinn1_0"
  | "red_vac_blinn1_0"
  | "stylus_blinn1_0"
  | "table_blinn1_0"
  | "tablet_blinn1_0"
  | "triangle_blinn1_0"
  | "vac_black_blinn1_0"
  | "vacuum1_blinn1_0"
  | "vacuumgrey_blinn1_0"
  | "vires_blinn1_0"
  | "window_blinn1_0"
  | "window4_phong1_0";

type RoomGLTF = GLTF & {
  nodes: Record<RoomNodeName, THREE.Mesh>;
  materials: {
    blinn1: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    phong1: THREE.MeshStandardMaterial;
  };
};

type RoomProps = ThreeElements["group"];

export function Room(props: RoomProps) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as RoomGLTF;
  const screensRef = useRef<THREE.Mesh>(null);
  const matcapTexture = useTexture("/images/textures/mat1.png");

  const customMaterials = useMemo(
    () => ({
      curtain: new THREE.MeshPhongMaterial({ color: "#006B68" }),
      body: new THREE.MeshPhongMaterial({
        color: "#00A19B",
        map: matcapTexture,
      }),
      table: new THREE.MeshPhongMaterial({ color: "#173B39" }),
      radiator: new THREE.MeshPhongMaterial({ color: "#E6F7F6" }),
      computer: new THREE.MeshStandardMaterial({ color: "#F4FBFA" }),
      pillow: new THREE.MeshPhongMaterial({ color: "#82D8D4" }),
      chair: new THREE.MeshPhongMaterial({ color: "#102D2C" }),
      accent: new THREE.MeshPhongMaterial({ color: "#00A19B" }),
    }),
    [matcapTexture],
  );

  useEffect(
    () => () => {
      Object.values(customMaterials).forEach((material) => material.dispose());
    },
    [customMaterials],
  );

  return (
    <>
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={1.5}
          luminanceThreshold={0.2}
          luminanceSmoothing={0.9}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      <group {...props} dispose={null}>
        <mesh
          geometry={nodes._________6_blinn1_0.geometry}
          material={customMaterials.curtain}
        />
        <mesh
          geometry={nodes.body1_blinn1_0.geometry}
          material={customMaterials.body}
        />
        <mesh
          geometry={nodes.cabin_blinn1_0.geometry}
          material={customMaterials.table}
        />
        <mesh
          geometry={nodes.chair_body_blinn1_0.geometry}
          material={customMaterials.chair}
        />
        <mesh
          geometry={nodes.comp_blinn1_0.geometry}
          material={customMaterials.computer}
        />
        <mesh
          ref={screensRef}
          geometry={nodes.emis_lambert1_0.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.handls_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.keyboard_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.kovrik_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.lamp_bl_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.lamp_white_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.miuse_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.monitor2_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.monitor3_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.pCylinder5_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.pillows_blinn1_0.geometry}
          material={customMaterials.pillow}
        />
        <mesh
          geometry={nodes.polySurface53_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.radiator_blinn1_0.geometry}
          material={customMaterials.radiator}
        />
        <mesh
          geometry={nodes.radiator_blinn1_0001.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.railing_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.red_bttns_blinn1_0.geometry}
          material={customMaterials.accent}
        />
        <mesh
          geometry={nodes.red_vac_blinn1_0.geometry}
          material={customMaterials.accent}
        />
        <mesh
          geometry={nodes.stylus_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.table_blinn1_0.geometry}
          material={customMaterials.table}
        />
        <mesh
          geometry={nodes.tablet_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.triangle_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.vac_black_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.vacuum1_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.vacuumgrey_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.vires_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.window_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          geometry={nodes.window4_phong1_0.geometry}
          material={materials.phong1}
        />
      </group>
    </>
  );
}

useGLTF.preload(MODEL_PATH);

export default Room;